package com.app.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MoviesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movies
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movies
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movies
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public MoviesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movies
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMovienameIsNull() {
            addCriterion("movieName is null");
            return (Criteria) this;
        }

        public Criteria andMovienameIsNotNull() {
            addCriterion("movieName is not null");
            return (Criteria) this;
        }

        public Criteria andMovienameEqualTo(String value) {
            addCriterion("movieName =", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameNotEqualTo(String value) {
            addCriterion("movieName <>", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameGreaterThan(String value) {
            addCriterion("movieName >", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameGreaterThanOrEqualTo(String value) {
            addCriterion("movieName >=", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameLessThan(String value) {
            addCriterion("movieName <", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameLessThanOrEqualTo(String value) {
            addCriterion("movieName <=", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameLike(String value) {
            addCriterion("movieName like", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameNotLike(String value) {
            addCriterion("movieName not like", value, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameIn(List<String> values) {
            addCriterion("movieName in", values, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameNotIn(List<String> values) {
            addCriterion("movieName not in", values, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameBetween(String value1, String value2) {
            addCriterion("movieName between", value1, value2, "moviename");
            return (Criteria) this;
        }

        public Criteria andMovienameNotBetween(String value1, String value2) {
            addCriterion("movieName not between", value1, value2, "moviename");
            return (Criteria) this;
        }

        public Criteria andDirectorIsNull() {
            addCriterion("director is null");
            return (Criteria) this;
        }

        public Criteria andDirectorIsNotNull() {
            addCriterion("director is not null");
            return (Criteria) this;
        }

        public Criteria andDirectorEqualTo(String value) {
            addCriterion("director =", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorNotEqualTo(String value) {
            addCriterion("director <>", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorGreaterThan(String value) {
            addCriterion("director >", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorGreaterThanOrEqualTo(String value) {
            addCriterion("director >=", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorLessThan(String value) {
            addCriterion("director <", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorLessThanOrEqualTo(String value) {
            addCriterion("director <=", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorLike(String value) {
            addCriterion("director like", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorNotLike(String value) {
            addCriterion("director not like", value, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorIn(List<String> values) {
            addCriterion("director in", values, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorNotIn(List<String> values) {
            addCriterion("director not in", values, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorBetween(String value1, String value2) {
            addCriterion("director between", value1, value2, "director");
            return (Criteria) this;
        }

        public Criteria andDirectorNotBetween(String value1, String value2) {
            addCriterion("director not between", value1, value2, "director");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andPublishdateIsNull() {
            addCriterion("publishDate is null");
            return (Criteria) this;
        }

        public Criteria andPublishdateIsNotNull() {
            addCriterion("publishDate is not null");
            return (Criteria) this;
        }

        public Criteria andPublishdateEqualTo(String value) {
            addCriterion("publishDate =", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotEqualTo(String value) {
            addCriterion("publishDate <>", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateGreaterThan(String value) {
            addCriterion("publishDate >", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateGreaterThanOrEqualTo(String value) {
            addCriterion("publishDate >=", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLessThan(String value) {
            addCriterion("publishDate <", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLessThanOrEqualTo(String value) {
            addCriterion("publishDate <=", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLike(String value) {
            addCriterion("publishDate like", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotLike(String value) {
            addCriterion("publishDate not like", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateIn(List<String> values) {
            addCriterion("publishDate in", values, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotIn(List<String> values) {
            addCriterion("publishDate not in", values, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateBetween(String value1, String value2) {
            addCriterion("publishDate between", value1, value2, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotBetween(String value1, String value2) {
            addCriterion("publishDate not between", value1, value2, "publishdate");
            return (Criteria) this;
        }

        public Criteria andBoxofficeIsNull() {
            addCriterion("boxOffice is null");
            return (Criteria) this;
        }

        public Criteria andBoxofficeIsNotNull() {
            addCriterion("boxOffice is not null");
            return (Criteria) this;
        }

        public Criteria andBoxofficeEqualTo(Long value) {
            addCriterion("boxOffice =", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeNotEqualTo(Long value) {
            addCriterion("boxOffice <>", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeGreaterThan(Long value) {
            addCriterion("boxOffice >", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeGreaterThanOrEqualTo(Long value) {
            addCriterion("boxOffice >=", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeLessThan(Long value) {
            addCriterion("boxOffice <", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeLessThanOrEqualTo(Long value) {
            addCriterion("boxOffice <=", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeIn(List<Long> values) {
            addCriterion("boxOffice in", values, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeNotIn(List<Long> values) {
            addCriterion("boxOffice not in", values, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeBetween(Long value1, Long value2) {
            addCriterion("boxOffice between", value1, value2, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeNotBetween(Long value1, Long value2) {
            addCriterion("boxOffice not between", value1, value2, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceIsNull() {
            addCriterion("ticketPrice is null");
            return (Criteria) this;
        }

        public Criteria andTicketpriceIsNotNull() {
            addCriterion("ticketPrice is not null");
            return (Criteria) this;
        }

        public Criteria andTicketpriceEqualTo(Long value) {
            addCriterion("ticketPrice =", value, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceNotEqualTo(Long value) {
            addCriterion("ticketPrice <>", value, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceGreaterThan(Long value) {
            addCriterion("ticketPrice >", value, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("ticketPrice >=", value, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceLessThan(Long value) {
            addCriterion("ticketPrice <", value, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceLessThanOrEqualTo(Long value) {
            addCriterion("ticketPrice <=", value, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceIn(List<Long> values) {
            addCriterion("ticketPrice in", values, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceNotIn(List<Long> values) {
            addCriterion("ticketPrice not in", values, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceBetween(Long value1, Long value2) {
            addCriterion("ticketPrice between", value1, value2, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andTicketpriceNotBetween(Long value1, Long value2) {
            addCriterion("ticketPrice not between", value1, value2, "ticketprice");
            return (Criteria) this;
        }

        public Criteria andSessionIsNull() {
            addCriterion("session is null");
            return (Criteria) this;
        }

        public Criteria andSessionIsNotNull() {
            addCriterion("session is not null");
            return (Criteria) this;
        }

        public Criteria andSessionEqualTo(String value) {
            addCriterion("session =", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionNotEqualTo(String value) {
            addCriterion("session <>", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionGreaterThan(String value) {
            addCriterion("session >", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionGreaterThanOrEqualTo(String value) {
            addCriterion("session >=", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionLessThan(String value) {
            addCriterion("session <", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionLessThanOrEqualTo(String value) {
            addCriterion("session <=", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionLike(String value) {
            addCriterion("session like", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionNotLike(String value) {
            addCriterion("session not like", value, "session");
            return (Criteria) this;
        }

        public Criteria andSessionIn(List<String> values) {
            addCriterion("session in", values, "session");
            return (Criteria) this;
        }

        public Criteria andSessionNotIn(List<String> values) {
            addCriterion("session not in", values, "session");
            return (Criteria) this;
        }

        public Criteria andSessionBetween(String value1, String value2) {
            addCriterion("session between", value1, value2, "session");
            return (Criteria) this;
        }

        public Criteria andSessionNotBetween(String value1, String value2) {
            addCriterion("session not between", value1, value2, "session");
            return (Criteria) this;
        }

        public Criteria andVideohallIsNull() {
            addCriterion("videoHall is null");
            return (Criteria) this;
        }

        public Criteria andVideohallIsNotNull() {
            addCriterion("videoHall is not null");
            return (Criteria) this;
        }

        public Criteria andVideohallEqualTo(String value) {
            addCriterion("videoHall =", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallNotEqualTo(String value) {
            addCriterion("videoHall <>", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallGreaterThan(String value) {
            addCriterion("videoHall >", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallGreaterThanOrEqualTo(String value) {
            addCriterion("videoHall >=", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallLessThan(String value) {
            addCriterion("videoHall <", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallLessThanOrEqualTo(String value) {
            addCriterion("videoHall <=", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallLike(String value) {
            addCriterion("videoHall like", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallNotLike(String value) {
            addCriterion("videoHall not like", value, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallIn(List<String> values) {
            addCriterion("videoHall in", values, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallNotIn(List<String> values) {
            addCriterion("videoHall not in", values, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallBetween(String value1, String value2) {
            addCriterion("videoHall between", value1, value2, "videohall");
            return (Criteria) this;
        }

        public Criteria andVideohallNotBetween(String value1, String value2) {
            addCriterion("videoHall not between", value1, value2, "videohall");
            return (Criteria) this;
        }

        public Criteria andImgpathIsNull() {
            addCriterion("imgpath is null");
            return (Criteria) this;
        }

        public Criteria andImgpathIsNotNull() {
            addCriterion("imgpath is not null");
            return (Criteria) this;
        }

        public Criteria andImgpathEqualTo(String value) {
            addCriterion("imgpath =", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotEqualTo(String value) {
            addCriterion("imgpath <>", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathGreaterThan(String value) {
            addCriterion("imgpath >", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathGreaterThanOrEqualTo(String value) {
            addCriterion("imgpath >=", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathLessThan(String value) {
            addCriterion("imgpath <", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathLessThanOrEqualTo(String value) {
            addCriterion("imgpath <=", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathLike(String value) {
            addCriterion("imgpath like", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotLike(String value) {
            addCriterion("imgpath not like", value, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathIn(List<String> values) {
            addCriterion("imgpath in", values, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotIn(List<String> values) {
            addCriterion("imgpath not in", values, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathBetween(String value1, String value2) {
            addCriterion("imgpath between", value1, value2, "imgpath");
            return (Criteria) this;
        }

        public Criteria andImgpathNotBetween(String value1, String value2) {
            addCriterion("imgpath not between", value1, value2, "imgpath");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andHotIsNull() {
            addCriterion("hot is null");
            return (Criteria) this;
        }

        public Criteria andHotIsNotNull() {
            addCriterion("hot is not null");
            return (Criteria) this;
        }

        public Criteria andHotEqualTo(Integer value) {
            addCriterion("hot =", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotEqualTo(Integer value) {
            addCriterion("hot <>", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThan(Integer value) {
            addCriterion("hot >", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThanOrEqualTo(Integer value) {
            addCriterion("hot >=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThan(Integer value) {
            addCriterion("hot <", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThanOrEqualTo(Integer value) {
            addCriterion("hot <=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotIn(List<Integer> values) {
            addCriterion("hot in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotIn(List<Integer> values) {
            addCriterion("hot not in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotBetween(Integer value1, Integer value2) {
            addCriterion("hot between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotBetween(Integer value1, Integer value2) {
            addCriterion("hot not between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andIszsqdIsNull() {
            addCriterion("iszsqd is null");
            return (Criteria) this;
        }

        public Criteria andIszsqdIsNotNull() {
            addCriterion("iszsqd is not null");
            return (Criteria) this;
        }

        public Criteria andIszsqdEqualTo(String value) {
            addCriterion("iszsqd =", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdNotEqualTo(String value) {
            addCriterion("iszsqd <>", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdGreaterThan(String value) {
            addCriterion("iszsqd >", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdGreaterThanOrEqualTo(String value) {
            addCriterion("iszsqd >=", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdLessThan(String value) {
            addCriterion("iszsqd <", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdLessThanOrEqualTo(String value) {
            addCriterion("iszsqd <=", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdLike(String value) {
            addCriterion("iszsqd like", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdNotLike(String value) {
            addCriterion("iszsqd not like", value, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdIn(List<String> values) {
            addCriterion("iszsqd in", values, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdNotIn(List<String> values) {
            addCriterion("iszsqd not in", values, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdBetween(String value1, String value2) {
            addCriterion("iszsqd between", value1, value2, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIszsqdNotBetween(String value1, String value2) {
            addCriterion("iszsqd not between", value1, value2, "iszsqd");
            return (Criteria) this;
        }

        public Criteria andIshprcIsNull() {
            addCriterion("ishprc is null");
            return (Criteria) this;
        }

        public Criteria andIshprcIsNotNull() {
            addCriterion("ishprc is not null");
            return (Criteria) this;
        }

        public Criteria andIshprcEqualTo(String value) {
            addCriterion("ishprc =", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcNotEqualTo(String value) {
            addCriterion("ishprc <>", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcGreaterThan(String value) {
            addCriterion("ishprc >", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcGreaterThanOrEqualTo(String value) {
            addCriterion("ishprc >=", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcLessThan(String value) {
            addCriterion("ishprc <", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcLessThanOrEqualTo(String value) {
            addCriterion("ishprc <=", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcLike(String value) {
            addCriterion("ishprc like", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcNotLike(String value) {
            addCriterion("ishprc not like", value, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcIn(List<String> values) {
            addCriterion("ishprc in", values, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcNotIn(List<String> values) {
            addCriterion("ishprc not in", values, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcBetween(String value1, String value2) {
            addCriterion("ishprc between", value1, value2, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIshprcNotBetween(String value1, String value2) {
            addCriterion("ishprc not between", value1, value2, "ishprc");
            return (Criteria) this;
        }

        public Criteria andIsjrpfIsNull() {
            addCriterion("isjrpf is null");
            return (Criteria) this;
        }

        public Criteria andIsjrpfIsNotNull() {
            addCriterion("isjrpf is not null");
            return (Criteria) this;
        }

        public Criteria andIsjrpfEqualTo(String value) {
            addCriterion("isjrpf =", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfNotEqualTo(String value) {
            addCriterion("isjrpf <>", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfGreaterThan(String value) {
            addCriterion("isjrpf >", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfGreaterThanOrEqualTo(String value) {
            addCriterion("isjrpf >=", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfLessThan(String value) {
            addCriterion("isjrpf <", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfLessThanOrEqualTo(String value) {
            addCriterion("isjrpf <=", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfLike(String value) {
            addCriterion("isjrpf like", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfNotLike(String value) {
            addCriterion("isjrpf not like", value, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfIn(List<String> values) {
            addCriterion("isjrpf in", values, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfNotIn(List<String> values) {
            addCriterion("isjrpf not in", values, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfBetween(String value1, String value2) {
            addCriterion("isjrpf between", value1, value2, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andIsjrpfNotBetween(String value1, String value2) {
            addCriterion("isjrpf not between", value1, value2, "isjrpf");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("updatedate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("updatedate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("updatedate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("updatedate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("updatedate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("updatedate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("updatedate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("updatedate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("updatedate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("updatedate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movies
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movies
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}