package com.app.bean;

import java.util.Date;

public class Movies {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.movieName
     *
     * @mbggenerated
     */
    private String moviename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.director
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.publishDate
     *
     * @mbggenerated
     */
    private String publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.boxOffice
     *
     * @mbggenerated
     */
    private Long boxoffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.ticketPrice
     *
     * @mbggenerated
     */
    private Long ticketprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.session
     *
     * @mbggenerated
     */
    private String session;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.videoHall
     *
     * @mbggenerated
     */
    private String videohall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.imgpath
     *
     * @mbggenerated
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.hot
     *
     * @mbggenerated
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.iszsqd
     *
     * @mbggenerated
     */
    private String iszsqd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.ishprc
     *
     * @mbggenerated
     */
    private String ishprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.isjrpf
     *
     * @mbggenerated
     */
    private String isjrpf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.updatedate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.id
     *
     * @return the value of movies.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.id
     *
     * @param id the value for movies.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.movieName
     *
     * @return the value of movies.movieName
     *
     * @mbggenerated
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.movieName
     *
     * @param moviename the value for movies.movieName
     *
     * @mbggenerated
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.director
     *
     * @return the value of movies.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.director
     *
     * @param director the value for movies.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.time
     *
     * @return the value of movies.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.time
     *
     * @param time the value for movies.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.language
     *
     * @return the value of movies.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.language
     *
     * @param language the value for movies.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.publishDate
     *
     * @return the value of movies.publishDate
     *
     * @mbggenerated
     */
    public String getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.publishDate
     *
     * @param publishdate the value for movies.publishDate
     *
     * @mbggenerated
     */
    public void setPublishdate(String publishdate) {
        this.publishdate = publishdate == null ? null : publishdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.boxOffice
     *
     * @return the value of movies.boxOffice
     *
     * @mbggenerated
     */
    public Long getBoxoffice() {
        return boxoffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.boxOffice
     *
     * @param boxoffice the value for movies.boxOffice
     *
     * @mbggenerated
     */
    public void setBoxoffice(Long boxoffice) {
        this.boxoffice = boxoffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.ticketPrice
     *
     * @return the value of movies.ticketPrice
     *
     * @mbggenerated
     */
    public Long getTicketprice() {
        return ticketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.ticketPrice
     *
     * @param ticketprice the value for movies.ticketPrice
     *
     * @mbggenerated
     */
    public void setTicketprice(Long ticketprice) {
        this.ticketprice = ticketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.session
     *
     * @return the value of movies.session
     *
     * @mbggenerated
     */
    public String getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.session
     *
     * @param session the value for movies.session
     *
     * @mbggenerated
     */
    public void setSession(String session) {
        this.session = session == null ? null : session.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.videoHall
     *
     * @return the value of movies.videoHall
     *
     * @mbggenerated
     */
    public String getVideohall() {
        return videohall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.videoHall
     *
     * @param videohall the value for movies.videoHall
     *
     * @mbggenerated
     */
    public void setVideohall(String videohall) {
        this.videohall = videohall == null ? null : videohall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.imgpath
     *
     * @return the value of movies.imgpath
     *
     * @mbggenerated
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.imgpath
     *
     * @param imgpath the value for movies.imgpath
     *
     * @mbggenerated
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.description
     *
     * @return the value of movies.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.description
     *
     * @param description the value for movies.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.hot
     *
     * @return the value of movies.hot
     *
     * @mbggenerated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.hot
     *
     * @param hot the value for movies.hot
     *
     * @mbggenerated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.iszsqd
     *
     * @return the value of movies.iszsqd
     *
     * @mbggenerated
     */
    public String getIszsqd() {
        return iszsqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.iszsqd
     *
     * @param iszsqd the value for movies.iszsqd
     *
     * @mbggenerated
     */
    public void setIszsqd(String iszsqd) {
        this.iszsqd = iszsqd == null ? null : iszsqd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.ishprc
     *
     * @return the value of movies.ishprc
     *
     * @mbggenerated
     */
    public String getIshprc() {
        return ishprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.ishprc
     *
     * @param ishprc the value for movies.ishprc
     *
     * @mbggenerated
     */
    public void setIshprc(String ishprc) {
        this.ishprc = ishprc == null ? null : ishprc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.isjrpf
     *
     * @return the value of movies.isjrpf
     *
     * @mbggenerated
     */
    public String getIsjrpf() {
        return isjrpf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.isjrpf
     *
     * @param isjrpf the value for movies.isjrpf
     *
     * @mbggenerated
     */
    public void setIsjrpf(String isjrpf) {
        this.isjrpf = isjrpf == null ? null : isjrpf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.updatedate
     *
     * @return the value of movies.updatedate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.updatedate
     *
     * @param updatedate the value for movies.updatedate
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}