package com.app.bean;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.movieid
     *
     * @mbggenerated
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.moviename
     *
     * @mbggenerated
     */
    private String moviename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seat
     *
     * @mbggenerated
     */
    private String seat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.occupy
     *
     * @mbggenerated
     */
    private String occupy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.id
     *
     * @return the value of ticket.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.id
     *
     * @param id the value for ticket.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.movieid
     *
     * @return the value of ticket.movieid
     *
     * @mbggenerated
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.movieid
     *
     * @param movieid the value for ticket.movieid
     *
     * @mbggenerated
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.moviename
     *
     * @return the value of ticket.moviename
     *
     * @mbggenerated
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.moviename
     *
     * @param moviename the value for ticket.moviename
     *
     * @mbggenerated
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seat
     *
     * @return the value of ticket.seat
     *
     * @mbggenerated
     */
    public String getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seat
     *
     * @param seat the value for ticket.seat
     *
     * @mbggenerated
     */
    public void setSeat(String seat) {
        this.seat = seat == null ? null : seat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.occupy
     *
     * @return the value of ticket.occupy
     *
     * @mbggenerated
     */
    public String getOccupy() {
        return occupy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.occupy
     *
     * @param occupy the value for ticket.occupy
     *
     * @mbggenerated
     */
    public void setOccupy(String occupy) {
        this.occupy = occupy == null ? null : occupy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.status
     *
     * @return the value of ticket.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.status
     *
     * @param status the value for ticket.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}