package com.app.mapper;

import com.app.bean.Movies;
import com.app.bean.MoviesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoviesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int countByExample(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int deleteByExample(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int insert(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int insertSelective(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    List<Movies> selectByExample(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    Movies selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Movies record, @Param("example") MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Movies record, @Param("example") MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Movies record);
}